services:
  postgres:
    image: postgres:16-alpine
    container_name: energyMSI-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: energyMSI
      POSTGRES_PASSWORD: energyMSI123
      POSTGRES_DB: energyMSI_shop
    ports:
      - "5490:5432"

